### ISSUE TITLE
No information about license

### ISSUE THREAD

**Issue by en90** [kiasaki/docker-alpine-postgres#1]
Hello. Originally, I was planning on using Debian-based Docker images for PostgreSQL but after being reminded about Alpine Linux, I went to check if someone had made a Docker image of PostgreSQL and found your project which seems pretty nice. Unfortunatelly, with no license, I will not be able to use -- or even look at the source of -- this project.

Please consider adding a license to this project.

**Comment by kiasaki** [comment]
Good point, I can believe I didn't see this issue in my feed, will add one now.
