### ISSUE TITLE
ERROR: http://nl.alpinelinux.org/alpine/edge/main: IO ERROR

### ISSUE THREAD

**Issue by SerialVelocity** [kiasaki/docker-alpine-postgres#11]
Hey,

We're trying to use this package but we need to include postgres-contribs. Problem is, 50% of the time when we run:
```apk update && apk add "postgresql-contrib@edge>9.4"```
the update fails and we get:
```fetch http://alpine.gliderlabs.com/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: http://nl.alpinelinux.org/alpine/edge/main: IO ERROR
WARNING: Ignoring APKINDEX.1ebd6aac.tar.gz: No such file or directory
v3.2.3-232-g73bfff8 [http://alpine.gliderlabs.com/alpine/v3.2/main]
1 errors; 5293 distinct packages available```

Why are you pulling in the edge repository? By installing from edge, you are actually installing postgres 9.5 instead of 9.4.

Cheers,
SerialVelocity

**Comment by kiasaki** [comment]
Humm, indeed.

At the time this was screated edge had 9.4 and 9.5 didn't exist.

But, this means the 9.4 tag downloads 9.5 now.

I'll do a PR fixing the version to 9.4 and 9.5 for the respected tags, latest being 9.5 but I need to keep using edge for access to 9.5 (I think).

I'll add in `postgresql-contrib` I think many use cases need that package installed anyways.
