### ISSUE TITLE
Please, link your Docker Hub image to Alpine

### ISSUE THREAD

**Issue by frol** [kiasaki/docker-alpine-postgres#22]
Linking your image to the base image in Docker Hub image settings will keep your image up-to-date automatically! Please, do it.

**Comment by ivlis** [comment]
Done here:
https://hub.docker.com/r/ivlis/alpine-postgres/

**Comment by kiasaki** [comment]
Used to be there... Just logged in Docker Up (Now cloud I guess?)

They changed up everything and my automatic builds are now setup anymore.

Linked it back.

**Comment by kiasaki** [comment]
Sorry, in my last comment I mistaken Automated Builds with linking to the **base image**. (And that new docker cloud they have caused even more confusion)

Here:
![screen shot 2016-10-31 at 11 53 41 am](https://cloud.githubusercontent.com/assets/1158933/19860908/ece122e0-9f60-11e6-8088-6bc9416f9af7.png)

**Comment by frol** [comment]
Thank you!
