### ISSUE TITLE
9.6 and current releases of back versions?

### ISSUE THREAD

**Issue by tmornini** [kiasaki/docker-alpine-postgres#23]
Hello!

Thank you for these wonderful, tiny images!

Time for a refresh to current versions? I think so! :-)

Thank you again for this, I really appreciate it and don't take it for granted!

**Comment by kiasaki** [comment]
Yep, agreed.

This commit from @lospejos made it happen https://github.com/kiasaki/docker-alpine-postgres/commit/91422a62396fd65b8b4394b914285ad445533c3b

**Comment by kiasaki** [comment]
_Sorry for the response time, missed that issue on my GitHub feed ;)_

**Comment by tmornini** [comment]
@kiasaki Thank you for maintaining your projects! 👍
