### ISSUE TITLE
Instructions for creating containers

### ISSUE THREAD

**Issue by Kentoseth** [kiasaki/docker-alpine-postgres#6]
Can you please provide further instructions for creating a database container using the image that is created from this Dockerfile?

Although I was able to spin up a container with these instructions:

https://hub.docker.com/_/postgres/

More specifically, this line:

    docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres

It would really be helpful if your documentation explained it a bit further.

Thanks,

**Comment by kiasaki** [comment]
Sure, I think I mention the instructions are the same as for the official postgres image but it wouldn't hurt to have some basic ones in here.

Do you want to write a small PR for it or do you prefer to let me do it?

**Comment by Kentoseth** [comment]
I've since abandoned Docker for my use-case, but it may be useful for other future users of this dockerfile.

You probably also have better knowledge with the required commands, so it may be better for you to write it.

**Comment by kiasaki** [comment]
Good, will do!
