### ISSUE TITLE
Access via docker hub?

### ISSUE THREAD

**Issue by hhsnopek** [kiasaki/docker-alpine-postgres#9]
I can't figure out how I am to reference this repository in my `docker-compose.yml` file. What's the best way to go about this?

**Comment by kiasaki** [comment]
Ha! Yes it's on Docker Hub, sorry if this wasn't documented / clear. Here's the link: https://hub.docker.com/r/kiasaki/alpine-postgres/ :dancer: 

I'll add it to the README.

**Comment by kiasaki** [comment]
The name for it is: `kiasaki/alpine-postgres`

**Comment by hhsnopek** [comment]
thanks @kiasaki!! :smile:
